### ISSUE TITLE
 LiteCreditCardInput throwing Warning: componentWillReceiveProps has been renamed, and is not recommended for use on Focus

### ISSUE THREAD

**Issue by BobRusch** [juandl/react-native-credit-card-input-plus#1]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.     
* If you're updating state whenever props change, refactor your code 
to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: %s, CCInput, LiteCreditCardInput

**Comment by BobRusch** [comment]
Thanks for your quick response... Is there a timeframe for this enhancement? BTW: This package worked great until last React move. In the process of developing an E-Commerce app for iOS and android and this just started popping up. Thanks again

**Comment by juandl** [comment]
@BobRusch Sorry for delay reply, I wil look into it this week

**Comment by BobRusch** [comment]
Thanks, NP, it seems that react has again made a breaking change.

Bob

**Comment by Kiura** [comment]
Any plans to fix this soon?

**Comment by juandl** [comment]
@Kiura Next week will spend few hours for this hopefully

**Comment by kneza23** [comment]
also this is a problem, as it has same deprecation message `RCTUIManager.measureLayoutRelativeToParent`

**Comment by juandl** [comment]
Please check the latest release

**Comment by juandl** [comment]
> also this is a problem, as it has same deprecation message `RCTUIManager.measureLayoutRelativeToParent`

Please open a issue with the details, thank you
