### ISSUE TITLE
Change width of input containers and invalid postal code

### ISSUE THREAD

**Issue by marlene89** [juandl/react-native-credit-card-input-plus#10]
How do I change the width of the input containers?  I tried to add width in inputContainerStyle but it doesn't seem to have any effect.

**Comment by marlene89** [comment]
please note i disabled horizontal scrolling and have the fields in vertical orientation.

**Comment by marlene89** [comment]
![Screenshot_20230207-215527](https://user-images.githubusercontent.com/17938327/217351762-d962b4af-2dfd-405d-a05e-2453759943cc.png)

**Comment by marlene89** [comment]
something else i noticed is when I enter 91405 or 90292 as postal codes, the log says its an incomplete postal code although they are valid postal codes. Would you happen to know why this is happening?

**Comment by juandl** [comment]
> How do I change the width of the input containers? I tried to add width in inputContainerStyle but it doesn't seem to have any effect.

Have you tried "inputStyle" ? @marlene89

**Comment by marlene89** [comment]
> > How do I change the width of the input containers? I tried to add width in inputContainerStyle but it doesn't seem to have any effect.
> 
> Have you tried "inputStyle" ? @marlene89

Does not have any effect either.

**Comment by juandl** [comment]
@marlene89 I'm pushing an update this weekend, will try to check this

**Comment by juandl** [comment]
I'm happy to announce the new version! :rocket: [#0.4.7](https://github.com/juandl/react-native-credit-card-input-plus/releases/tag/v0.4.7), please check it out!

**Comment by juandl** [comment]
@marlene89 you can now use "inputContainerStyle" and postal code is fixed!
