### ISSUE TITLE
Mastercard default icon bug

### ISSUE THREAD

**Issue by ekiziltas** [juandl/react-native-credit-card-input-plus#14]
Even if "mastercard" is determined as type at onChange method, it is defined in icons file as "master-card" with additional dash.

**Comment by juandl** [comment]
Can you explain a bit more your issue or give a clear example, please.

**Comment by ekiziltas** [comment]
> Can you explain a bit more your issue or give a clear example, please.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/13187734/231305211-6d5d1da4-33c2-4653-888f-f047e31126d0.png">
This card is mastercard but icon is not shown. 

The solution is change "**master-card**" to "**mastercard**" in `src/Icons.js` file. That's all.

**Comment by CommanderAlchemy** [comment]
Hm not sure if this was updated but odly enough I have similar but different issue. 
`icons.js` now needs "mastercard" as key since the detection uses "mastercard" as key.

**Comment by juandl** [comment]
Solved, please update latest version
