### ISSUE TITLE
testID doesnt working on iOS

### ISSUE THREAD

**Issue by designervoid** [juandl/react-native-credit-card-input-plus#2]
https://github.com/sbycrosz/react-native-credit-card-input/issues/161#issuecomment-752177956
cant find `Identifier` in `xCode`.
https://github.com/wix/detox/blob/master/docs/Troubleshooting.RunningTests.md#debug-view-hierarchy
look how to debug view hierarchy in xCode.

**Comment by juandl** [comment]
I'm happy to announce the new version! :rocket: [#0.4.7](https://github.com/juandl/react-native-credit-card-input-plus/releases/tag/v0.4.7), please check it out!
