### ISSUE TITLE
Could you upgrade the card-validator to the latest?

### ISSUE THREAD

**Issue by Dylan0916** [juandl/react-native-credit-card-input-plus#3]
At present, `card-validator` is far away from the latest version. It is provided in a certain version to change the value of `maxLength`. I need it

**Comment by juandl** [comment]
@Dylan0916 I will work on it :)

**Comment by juandl** [comment]
I'm happy to announce the new version! :rocket: [#0.4.7](https://github.com/juandl/react-native-credit-card-input-plus/releases/tag/v0.4.7), please check it out!
