### ISSUE TITLE
React Native 0.70.3 ViewPropTypes Removed

### ISSUE THREAD

**Issue by monto020** [juandl/react-native-credit-card-input-plus#7]
Environment:
- react-native: 0.70.3
- react: 18.1.0
- react-native-credit-card-input-plus: 0.4.4 
- device: iPhone 12 pro, iOS 16.1 

Attempting to import and use the CreditCardInput component results in the attached error output (app crashing due to ViewPropTypes being removed): 
![Screenshot 2023-01-07 at 8 52 55 AM](https://user-images.githubusercontent.com/21693921/211161829-3fb8adfc-0575-446f-be5f-3d94674998e8.png)

**Comment by juandl** [comment]
Will work on it! Thank you!

**Comment by juandl** [comment]
Please check the latest version! should work well, I remove deprecated props

**Comment by MatheusRyuki** [comment]
Same problem happening at now


Environment:

react-native: 0.70.5
react: 18.1.0
react-native-credit-card-input-plus: 0.4.5

**Comment by juandl** [comment]
I'm happy to announce the new version! :rocket: [#0.4.7](https://github.com/juandl/react-native-credit-card-input-plus/releases/tag/v0.4.7), please check it out!
