### ISSUE TITLE
Could you change the react-native-flip-card dependency?

### ISSUE THREAD

**Issue by caballerof** [juandl/react-native-credit-card-input-plus#8]
react-native-flip-card V.3.5.6 is using ViewPropTypes. It is triggering the error:

`Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'`

There is a PR on the repository: https://github.com/moschan/react-native-flip-card/pull/108 to fix the issue. But the project was abandoned. Maybe you can make a fork and apply the fix.

**Comment by juandl** [comment]
@caballerof  mmm let me check that, i think we can just do a patch, will work on it, thank you for report it!

**Comment by jeremypagley** [comment]
@juandl Any update on this would love to use the lite card input

**Comment by RonJonesTalitrix** [comment]
Having this issue as well

**Comment by juandl** [comment]
Will push an update this weekend

**Comment by RonJonesTalitrix** [comment]
Thank you! Will you put the steps to fix here or is it as simple as updating the package?

**Comment by juandl** [comment]
what version of "react-native-credit-card-input-plus" are you using? @RonJonesTalitrix ?

**Comment by juandl** [comment]
I'm happy to announce the new version! :rocket: [#0.4.7](https://github.com/juandl/react-native-credit-card-input-plus/releases/tag/v0.4.7), please check it out!

**Comment by RonJonesTalitrix** [comment]
@juandl I am getting this error, 
"Could not find a declaration file for module 'react-native-credit-card-input-plus'. '/Users/ronjones/talitrix-cms/node_modules/react-native-credit-card-input-plus/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-credit-card-input-plus` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-credit-card-input-plus'"  
any tips?

**Comment by juandl** [comment]
@RonJonesTalitrix is this for TS? if is so, can you make another issue mention it please. Thank you

**Comment by RonJonesTalitrix** [comment]
@juandl done!
